---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ansibleee-openstack-org-v1alpha1-openstackansibleee
  failurePolicy: Fail
  name: mopenstackansibleee.kb.io
  rules:
  - apiGroups:
    - ansibleee.openstack.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackansibleees
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ansibleee-openstack-org-v1alpha1-openstackansibleee
  failurePolicy: Fail
  name: vopenstackansibleee.kb.io
  rules:
  - apiGroups:
    - ansibleee.openstack.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackansibleees
  sideEffects: None
