apiVersion: ansibleee.openstack.org/v1alpha1
kind: OpenStackAnsibleEE
metadata:
  name: ansibleee-test
  namespace: openstack
spec:
  playbook: "test.yaml"
  image: quay.io/openstack-k8s-operators/openstack-ansibleee-runner:latest
  inventory: |
          all:
            hosts:
              localhost
  extraMounts:
    - extraVolType: Ceph
      volumes:
      - name: ceph
        secret:
          secretName: ceph-client-conf
      mounts:
      - name: ceph
        mountPath: "/etc/ceph"
        readOnly: true
