apiVersion: ansibleee.openstack.org/v1beta1
kind: OpenStackAnsibleEE
metadata:
  name: ansibleee-play
  namespace: openstack
spec:
  image: quay.io/openstack-k8s-operators/openstack-ansibleee-runner:latest
  play: |
    - name: Print hello world
      hosts: all
      tasks:
      - name: Using debug statement
        ansible.builtin.debug:
          msg: "Hello, world this is ansibleee-play.yaml"
  extraMounts:
    - volumes:
      - name: inventory
        configMap:
          name: inventory-configmap
      - name: sshkey
        secret:
          secretName: ssh-key-secret
          items:
          - key: ssh-privatekey
            path: ssh_key
      mounts:
      - name: inventory
        mountPath: /runner/inventory/inventory.yaml
        subPath: inventory.yaml
      - name: sshkey
        mountPath: /runner/env/ssh_key
        subPath: ssh_key
