apiVersion: ansibleee.openstack.org/v1beta1
kind: OpenStackAnsibleEE
metadata:
  name: ansibleee-playbook-local
  namespace: openstack
spec:
  playbookContents: |
    - name: Print hello world
      hosts: all
      tasks:
      - name: Using debug statement
        ansible.builtin.debug:
          msg: "Hello, world! This is openstack-ansibleee-play.yaml"
  inventory: |
    all:
      vars:
        ansible_connection: local
      hosts:
        localhost
  env:
    - name: ANSIBLE_FORCE_COLOR
      value: "True"
    - name: ANSIBLE_SSH_ARGS
      value: "-C -o ControlMaster=auto -o ControlPersist=80s"
  extraMounts:
    - extraVolType: Ceph
      volumes:
      - name: ceph
        secret:
          secretName: ceph-client-conf
      mounts:
      - name: ceph
        mountPath: "/etc/ceph"
        readOnly: true
